[package]
name = "howrate"
version = "0.1.0"
authors = ["Tim DuBois <tim@neophilus.net>"]
edition = "2018"

[dependencies]
raft = { version="0.6.0-alpha", default-features = false, features = ["prost-codec"] }
